import os
import pickle
import numpy as np

# Path to the pre-trained artifacts generated by train_model.py
_BASE = os.path.dirname(__file__)
_MODEL_DIR = os.path.join(_BASE, "..", "model_artifacts")

VECTORIZER_PATH = os.path.join(_MODEL_DIR, "tfidf_vectorizer.pkl")
CLASSIFIER_PATH = os.path.join(_MODEL_DIR, "phishing_classifier.pkl")

class PhishingModel:
    def __init__(self):
        self.load_model()

    def load_model(self):
        """Load or reload model artifacts from disk."""
        if os.path.exists(VECTORIZER_PATH) and os.path.exists(CLASSIFIER_PATH):
            # Load the real pre-trained model trained on the SMS Spam Collection Dataset
            print(f"[PhishingModel] Loading model from {CLASSIFIER_PATH}...")
            with open(VECTORIZER_PATH, "rb") as f:
                self.vectorizer = pickle.load(f)
            with open(CLASSIFIER_PATH, "rb") as f:
                self.clf = pickle.load(f)
            self._is_ml_model = True
            print("[PhishingModel] ✓ Model loaded successfully.")
        else:
            # Fallback: small synthetic in-memory model if pkl files don't exist
            print("[PhishingModel] WARNING: Pre-trained model not found, using in-memory fallback.")
            self._is_ml_model = False
            self._train_fallback()

    def _train_fallback(self):
        """Train a small in-memory model as a fallback (no pkl files found)."""
        from sklearn.feature_extraction.text import TfidfVectorizer
        from sklearn.linear_model import LogisticRegression

        self.vectorizer = TfidfVectorizer(lowercase=True, stop_words="english", max_features=1000)
        self.clf = LogisticRegression(class_weight="balanced", random_state=42)

        training_data = [
            ("URGENT: Your account has been suspended. Verify your login immediately.", 1),
            ("Click here to claim your $1000 Amazon gift card! Limited time.", 1),
            ("Security Alert: Unusual activity on your bank account. Reset password now.", 1),
            ("You have won the lottery! Send bank details to transfer funds.", 1),
            ("Your PayPal account is restricted. Update billing information.", 1),
            ("Final notice: Pay your overdue tax bill or face legal action.", 1),
            ("Hey team, here is the agenda for tomorrow's marketing meeting.", 0),
            ("Don't forget we have lunch at noon today at the deli.", 0),
            ("Your monthly subscription receipt from Netflix is attached.", 0),
            ("Can you review my pull request for the new UI component?", 0),
            ("Thanks for signing up for our newsletter! We are excited!", 0),
            ("Reminder: Your doctor appointment is next Tuesday at 10 AM.", 0),
        ]

        texts  = [d[0] for d in training_data]
        labels = [d[1] for d in training_data]
        X = self.vectorizer.fit_transform(texts)
        self.clf.fit(X, np.array(labels))

    def get_explanation(self, text: str) -> list[str]:
        """Use TF-IDF × Logistic Regression coefficients to explain the classification."""
        X_test = self.vectorizer.transform([text])
        feature_names = self.vectorizer.get_feature_names_out()

        # Contribution = TF-IDF value × learned coefficient for the phishing class
        contributions = X_test.toarray()[0] * self.clf.coef_[0]
        top_indices = np.argsort(contributions)[::-1]

        explanations = []
        for idx in top_indices:
            if contributions[idx] > 0.05:
                word = feature_names[idx]
                explanations.append(f"ML flagged suspicious term: '{word}'")
                if len(explanations) >= 4:
                    break

        return explanations

    def predict_proba(self, text: str) -> float:
        """Return the probability that the text is phishing/spam."""
        if not text.strip():
            return 0.0
        X_test = self.vectorizer.transform([text])
        # Index 1 = Phishing/Spam class
        return float(self.clf.predict_proba(X_test)[0][1])

    def predict(self, text: str) -> bool:
        return self.predict_proba(text) > 0.5
